# Real Estate Analysis

## Importing Libraries and Datasets

In [2882]:
import warnings
warnings.filterwarnings('ignore')

import os
import pandas as pd
import mysql.connector
import sqlite3
from dotenv import load_dotenv
import matplotlib.pyplot as plt
from tabulate import tabulate
from decimal import Decimal, ROUND_HALF_UP
import seaborn as sns

In [2883]:
# Creating dataframes
agents_df = pd.read_json('Datasets/agents_cleaned.json')
buyers_df = pd.read_json('Datasets/buyers_cleaned.json')
listings_df = pd.read_json('Datasets/listings_final_expanded.json')
prop_att_df = pd.read_json('Datasets/property_attributes_final_expanded.json')
sales_df = pd.read_csv('Datasets/sales_cleaned.csv')

## Data Preparation and Cleaning

In [2884]:
# Percentage of missing values
def per_miss_val(df):
  return 100 * df.isnull().sum() / len(df)

# Convert bool to int
def bool_to_int(x):
  return x.map({True: 1, False: 0})

# Rounding to 2 decimals
def round_decimals(x):
  value = Decimal(x)
  rounded = value.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
  return rounded

### Agents

In [2885]:
# First 5 rows
agents_df.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.30,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.80,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.60,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.50,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.30,16,67

In [2886]:
# Last 5 rows
agents_df.tail()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
45,A0046,Agent A0046,+1-873-939-2900,a0046@realestate.com,1.57,135,3.20,10,58
46,A0047,Agent A0047,+1-153-271-8602,a0047@realestate.com,1.63,91,4.00,16,33
47,A0048,Agent A0048,+1-508-587-5937,a0048@realestate.com,1.34,266,4.00,21,15
48,A0049,Agent A0049,+1-587-864-9724,a0049@realestate.com,1.70,17,4.10,14,33
49,A0050,Agent A0050,+1-339-488-7390,a0050@realestate.com,2.56,109,3.50,11,68

In [2887]:
# Basic Information
agents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          50 non-null     object
 1   Name              50 non-null     object
 2   Phone             50 non-null     object
 3   Email             50 non-null     object
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

In [2888]:
# Shape
agents_df.shape

(50, 9)

In [2889]:
# Removing "Name" column
agents_df.drop(columns='Name', inplace=True)
agents_df.head()

,Agent_ID,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.30,10,64
1,A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.80,20,82
2,A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.60,21,83
3,A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.50,5,61
4,A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.30,16,67

In [2890]:
# Formatting the phone number
from re import split

def format_number(st):
  split_lst = st.split('-')
  phone_number = ''
  for i in split_lst:
    phone_number += i
  #country_code = split_lst[0].replace('+','')
  #phone_number = ''
  #for i in range(1, len(split_lst)):
    #phone_number += split_lst[i]

  return phone_number

#agents_df['Country Code'] = agents_df.Phone.apply(lambda x: format_number(x)[0]).astype(int)
agents_df['Phone'] = agents_df.Phone.apply(lambda x: format_number(x))
agents_df = agents_df[
  ['Agent_ID', 'Email', 'Phone', 'commission_rate', 'deals_closed', 'rating', 'experience_years', 'avg_closing_days']
  ]
agents_df.head()

,Agent_ID,Email,Phone,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,a0001@realestate.com,+15346658373,2.00,52,4.30,10,64
1,A0002,a0002@realestate.com,+14934634698,2.20,26,3.80,20,82
2,A0003,a0003@realestate.com,+12905341121,2.85,297,3.60,21,83
3,A0004,a0004@realestate.com,+16916104878,1.67,31,4.50,5,61
4,A0005,a0005@realestate.com,+18296135411,1.11,198,4.30,16,67

In [2891]:
# Missing values
per_miss_val(agents_df)

Agent_ID           0.00
Email              0.00
Phone              0.00
commission_rate    0.00
deals_closed       0.00
rating             0.00
experience_years   0.00
avg_closing_days   0.00
dtype: float64

In [2892]:
# Summary Statistics
agents_df.describe(include='all')

,Agent_ID,Email,Phone,commission_rate,deals_closed,rating,experience_years,avg_closing_days
count,50,50,50,50.00,50.00,50.00,50.00,50.00
unique,50,50,50,NaN,NaN,NaN,NaN,NaN
top,A0001,a0001@realestate.com,+15346658373,NaN,NaN,NaN,NaN,NaN
freq,1,1,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2.05,136.64,3.94,14.78,55.68
std,NaN,NaN,NaN,0.51,91.19,0.58,6.52,21.41
min,NaN,NaN,NaN,1.11,11.00,3.10,1.00,15.00
25%,NaN,NaN,NaN,1.64,60.75,3.50,10.25,35.25
50%,NaN,NaN,NaN,1.98,118.00,4.00,16.00,59.00
75%,NaN,NaN,NaN,2.51,225.75,4.30,20.00,75.00
max,NaN,NaN,NaN,2.96,297.00,5.00,25.00,90.00

### Property Attributes

In [2893]:
# First 5 rows
prop_att_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [2894]:
# Last 5 rows
prop_att_df.tail()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
21195,21196,L21196,5,4,3,6,2018,True,2,Semi-Furnished,6.21,True,True
21196,21197,L21197,5,1,0,33,2010,False,0,Unfurnished,2.16,False,True
21197,21198,L21198,5,2,7,29,1992,True,4,Semi-Furnished,6.60,True,True
21198,21199,L21199,5,3,20,21,2013,False,0,Semi-Furnished,1.76,False,False
21199,21200,L21200,4,2,9,30,2019,True,3,Furnished,12.12,False,False

In [2895]:
# Basic Information
prop_att_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [2896]:
# Converting boolean to integer
var_list = ['is_rented', 'parking_available', 'power_backup']

prop_att_df[var_list] = prop_att_df[var_list].apply(lambda x: bool_to_int(x))
prop_att_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,1,4,Furnished,7.26,0,1
1,2,L00002,2,2,19,29,2020,0,0,Unfurnished,4.84,1,0
2,3,L00003,2,3,8,26,2007,1,4,Semi-Furnished,4.92,0,0
3,4,L00004,3,3,25,10,2003,0,3,Furnished,1.20,0,1
4,5,L00005,2,2,15,16,2008,1,1,Semi-Furnished,7.90,0,0

In [2897]:
# Maintaining consistency with Column Name
prop_att_df.rename(columns={'listing_id': 'Listing_ID'}, inplace=True)
prop_att_df.head()

,attribute_id,Listing_ID,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,1,4,Furnished,7.26,0,1
1,2,L00002,2,2,19,29,2020,0,0,Unfurnished,4.84,1,0
2,3,L00003,2,3,8,26,2007,1,4,Semi-Furnished,4.92,0,0
3,4,L00004,3,3,25,10,2003,0,3,Furnished,1.20,0,1
4,5,L00005,2,2,15,16,2008,1,1,Semi-Furnished,7.90,0,0

In [2898]:
# Summary statistics
prop_att_df.describe(include='all')

,attribute_id,Listing_ID,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
count,21200.00,21200,21200.00,21200.00,21200.00,21200.00,21200.00,21200.00,21200.00,21200,21200.00,21200.00,21200.00
unique,NaN,21200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN
top,NaN,L00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unfurnished,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7210,NaN,NaN,NaN
mean,10600.50,NaN,3.00,2.50,9.64,20.10,2006.76,0.50,1.06,NaN,7.33,0.50,0.49
std,6120.06,NaN,1.41,1.12,8.53,11.14,9.82,0.50,1.43,NaN,4.29,0.50,0.50
min,1.00,NaN,1.00,1.00,0.00,1.00,1990.00,0.00,0.00,NaN,0.10,0.00,0.00
25%,5300.75,NaN,2.00,1.00,3.00,11.00,1998.00,0.00,0.00,NaN,3.63,0.00,0.00
50%,10600.50,NaN,3.00,2.00,7.00,20.00,2007.00,0.00,0.00,NaN,7.17,1.00,0.00
75%,15900.25,NaN,4.00,4.00,15.00,30.00,2015.00,1.00,2.00,NaN,11.01,1.00,1.00
max,21200.00,NaN,5.00,4.00,38.00,40.00,2023.00,1.00,4.00,NaN,15.00,1.00,1.00

### Buyers

In [2899]:
# First 5 rows
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [2900]:
# Last 5 rows
buyers_df.tail()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
19995,19996,L00891,Investor,UPI,False,None,0
19996,19997,L00834,End User,UPI,False,None,0
19997,19998,L01188,Investor,UPI,False,None,0
19998,19999,L00905,Investor,Cheque,True,ICICI,3701968
19999,20000,L00526,Investor,Cash,True,SBI,3805678

In [2901]:
# Convert boolean to integer in loan_taken column
buyers_df['loan_taken'] = buyers_df[['loan_taken']].apply(lambda x: bool_to_int(x))
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,None,0
1,2,L00866,Investor,Cheque,0,None,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,None,0
4,5,L00059,Investor,UPI,1,HDFC,4191221

In [2902]:
# Basic Information
buyers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  object
 2   buyer_type     20000 non-null  object
 3   payment_mode   20000 non-null  object
 4   loan_taken     20000 non-null  int64
 5   loan_provider  10034 non-null  object
 6   loan_amount    20000 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.1+ MB

In [2903]:
# Percentage of missing values
per_miss_val(buyers_df)

buyer_id         0.00
sale_id          0.00
buyer_type       0.00
payment_mode     0.00
loan_taken       0.00
loan_provider   49.83
loan_amount      0.00
dtype: float64

In [2904]:
# Checking if the loan provider is null for the buyer who has not taken a loan
buyers_df[buyers_df['loan_taken'] == 0]['loan_provider'].unique()

array([None], dtype=object)

In [2905]:
buyers_df[buyers_df['loan_amount'] == 0]['loan_provider'].unique()

array([None], dtype=object)

In [2906]:
# Fill null values with "NA"
buyers_df['loan_provider'].fillna('NA', inplace=True)
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,NA,0
1,2,L00866,Investor,Cheque,0,NA,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,NA,0
4,5,L00059,Investor,UPI,1,HDFC,4191221

In [2907]:
# Percentage of null values
per_miss_val(buyers_df)

buyer_id        0.00
sale_id         0.00
buyer_type      0.00
payment_mode    0.00
loan_taken      0.00
loan_provider   0.00
loan_amount     0.00
dtype: float64

In [2908]:
# Changing 'sale_id' column name to 'Listing_ID' to maintain consistency
buyers_df.rename(columns={'sale_id':'Listing_ID', 'payment_mode': 'Payment_Method'}, inplace=True)
buyers_df.head()

,buyer_id,Listing_ID,buyer_type,Payment_Method,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,NA,0
1,2,L00866,Investor,Cheque,0,NA,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,NA,0
4,5,L00059,Investor,UPI,1,HDFC,4191221

In [2909]:
# Summary Statistics
buyers_df.describe(include='all')

,buyer_id,Listing_ID,buyer_type,Payment_Method,loan_taken,loan_provider,loan_amount
count,20000.00,20000,20000,20000,20000.00,20000,20000.00
unique,NaN,720,2,4,NaN,6,NaN
top,NaN,L01179,End User,Cash,NaN,NA,NaN
freq,NaN,28,10020,5088,NaN,9966,NaN
mean,10000.50,NaN,NaN,NaN,0.50,NaN,2614323.05
std,5773.65,NaN,NaN,NaN,0.50,NaN,3252938.39
min,1.00,NaN,NaN,NaN,0.00,NaN,0.00
25%,5000.75,NaN,NaN,NaN,0.00,NaN,0.00
50%,10000.50,NaN,NaN,NaN,1.00,NaN,527295.50
75%,15000.25,NaN,NaN,NaN,1.00,NaN,5235048.75
max,20000.00,NaN,NaN,NaN,1.00,NaN,9997693.00

### Listings

In [2910]:
# First 5 rows
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144.01,2753.01,2023-05-06,A0015,33.97,-69.86
1,L00002,Los Angeles,Apartment,1519141.00,4966.99,2023-02-14,A0038,42.55,-90.28
2,L00003,Houston,Apartment,162489.00,1267.00,2023-04-22,A0015,28.73,-115.95
3,L00004,Phoenix,Apartment,1277015.98,2128.01,2024-01-02,A0042,26.40,-74.77
4,L00005,Phoenix,Townhouse,562297.01,4179.00,2023-10-29,A0018,39.43,-83.92

In [2911]:
# Last 5 rows
listings_df.tail()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
21195,L21196,Phoenix,House,709355.28,898.41,2023-12-31,A0021,25.46,-88.19
21196,L21197,Phoenix,Condo,3288420.13,4195.68,2023-07-23,A0005,40.93,-80.17
21197,L21198,Los Angeles,Apartment,1667441.24,8723.37,2024-06-30,A0003,46.08,-115.40
21198,L21199,Los Angeles,Townhouse,1648411.61,8412.71,2023-09-17,A0018,33.76,-103.47
21199,L21200,New York,Apartment,4991528.39,3994.92,2023-07-28,A0008,42.22,-119.22

In [2912]:
# Percentage of missing values
print("Percentage of missing values")
per_miss_val(listings_df)

Percentage of missing values

Listing_ID      0.00
City            0.00
Property_Type   0.00
Price           0.00
Sqft            0.00
Date_Listed     0.00
Agent_ID        0.00
Latitude        0.00
Longitude       0.00
dtype: float64

In [2913]:
# Basic Information
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  float64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  object
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.5+ MB

In [2914]:
# Standardising values in 'Price' and 'Sqft' columns
listings_df['Price'] = listings_df['Price'].apply(lambda x: round_decimals(x)).astype(float)
listings_df['Sqft'] = listings_df['Sqft'].apply(lambda x: round_decimals(x)).astype(float)

In [2915]:
# Summary Statistics
listings_df.describe(include='all')

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
count,21200,21200,21200,21200.00,21200.00,21200,21200,21200.00,21200.00
unique,21200,5,4,NaN,NaN,731,50,NaN,NaN
top,L00001,Los Angeles,Condo,NaN,NaN,2024-05-14,A0011,NaN,NaN
freq,1,4318,5363,NaN,NaN,46,463,NaN,NaN
mean,NaN,NaN,NaN,2452708.33,5113.38,NaN,NaN,37.01,-96.10
std,NaN,NaN,NaN,1419864.49,2737.68,NaN,NaN,6.93,16.73
min,NaN,NaN,NaN,100027.13,500.01,NaN,NaN,25.01,-125.00
25%,NaN,NaN,NaN,1216681.26,2768.28,NaN,NaN,30.97,-110.67
50%,NaN,NaN,NaN,2383802.92,4974.84,NaN,NaN,37.06,-96.16
75%,NaN,NaN,NaN,3679127.06,7488.90,NaN,NaN,42.95,-81.73
max,NaN,NaN,NaN,4999863.52,9999.59,NaN,NaN,49.00,-67.00

### Sales

In [2916]:
# First 5 rows
sales_df.head()

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179   925580.00  2023-07-07           65.01
1     L00866   105416.00  2023-06-14           38.00
2     L00102  1825184.00  2023-09-09           22.99
3     L00440  1932085.01  2023-10-29           72.01
4     L00059   776585.99  2023-05-01          116.00

In [2917]:
# Last 5 rows
sales_df.tail()

    Listing_ID  Sale_Price   Date_Sold  Days_on_Market
715     L00691   282092.01  2024-06-18          101.99
716     L00545  1917896.00  2023-12-16           33.01
717     L01123  1294669.98  2023-06-21           46.00
718     L00675  1398092.01  2024-04-15           50.00
719     L00690   503932.00  2023-05-13          119.00

In [2918]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    object
 1   Sale_Price      720 non-null    float64
 2   Date_Sold       720 non-null    object
 3   Days_on_Market  720 non-null    float64
dtypes: float64(2), object(2)
memory usage: 22.6+ KB

In [2919]:
sales_df.describe()

       Sale_Price  Days_on_Market
count      720.00          720.00
mean   1077545.92           61.64
std     542790.19           34.12
min     105416.00            4.99
25%     603148.25           30.75
50%    1076569.99           62.99
75%    1532235.02           91.02
max    2077611.01          120.02

## Connecting to MySQL

In [2920]:
load_dotenv()

conn = mysql.connector.connect(
  host = os.getenv('MYSQL_HOST'),
  user=os.getenv('MYSQL_USER'),
  password=os.getenv('MYSQL_PASSWORD')
)

cur = conn.cursor()

## Creating a Database 'Real_Estate'

In [2921]:
db_name = 'Real_Estate'

try:
  cur.execute("show databases like %s", (db_name,))
  result = cur.fetchone()


  if result:
    print(f"Database '{db_name}' already exists.")

  else:
    cur.execute(f'create database {db_name}')
    print(f"Database '{db_name}' created successfully.")

except Exception as e:
  print("Error Creating database: ", e)  

cur.fetchall()

Database 'Real_Estate' already exists.

[]

## Creating Tables in Real_Estate Database

In [2922]:
# Selecting the database
cur.execute("use Real_Estate")

In [2923]:
# Deleting if any table exists
cur.execute("drop table if exists agents")

#Creating agents table
create_table_query = """
    CREATE TABLE IF NOT EXISTS agents (
        Agent_ID VARCHAR(10),
        Email VARCHAR(100),
        Phone VARCHAR(20),
        Commission_Rate FLOAT,
        Deals_Closed INT,
        Rating FLOAT,
        Years_Of_Experience INT,
        Avg_Closing_Days INT
    )
    """

try:
    cur.execute(create_table_query)
    conn.commit()
    print("Agents Table Created Successfully.")
except mysql.connector.Error as e:
    print("Error: ", e)

Agents Table Created Successfully.

In [2924]:
# Deleting if buyers table exists
cur.execute('drop table if exists buyers')

# Creating buyers table
create_table_query = """
  create table if not exists buyers (
    Buyer_ID int,
    Listing_ID varchar(30),
    Buyer_Type varchar(40),
    Payment_Method varchar(30),
    Loan_Taken int,
    Loan_Provider varchar(30),
    Loan_Amount int 
  )
"""
try:
  cur.execute(create_table_query)
  conn.commit()
  print("Buyers Table Created Successfully.")
except mysql.connector.Error as e:
  print("Error: ", e)

Buyers Table Created Successfully.

In [2925]:
# Deleting if listings table exists
cur.execute('drop table if exists listings')

# Creating listings table
create_table_query = """
  create table if not exists listings (
    Listing_ID varchar(30),
    City varchar(50),
    Property_Type varchar(30),
    Price decimal(20,2),
    Sqft decimal(20,2),
    Date_Listed date,
    Agent_ID VARCHAR(10),
    Latitude float,
    Longitude float
  )
"""

try:
  cur.execute(create_table_query)
  conn.commit()
  print("Listings Table Created Successfully.")

except mysql.connector.Error as e:
  print("Error: ", e)

Listings Table Created Successfully.

In [2926]:
# Deleting if property_attributes table exists
cur.execute('drop table if exists property_attributes')

# Creating property_attributes table
create_table_query = """
  create table if not exists property_attributes (
    Attribute_ID int,
    Listing_ID varchar(30),
    Bedroom int,
    Bathroom int,
    Floor_Number int,
    Total_Floor int,
    Year_Built int,
    Is_Rented int,
    Tenant_Count int,
    Furnishing_Status varchar(30),
    Metro_Distance float,
    Parking_Available int,
    Power_Backup int
  )
"""
try:
  cur.execute(create_table_query)
  conn.commit()
  print("Property Attributes Table Created Successfully.")

except mysql.connector.Error as e:
  print("Error: ", e)

Property Attributes Table Created Successfully.

In [2927]:
# Deleting if sales table exists
cur.execute('drop table if exists sales')

# Creating sales table
create_table_query = """
  create table if not exists sales (
    Listing_ID varchar(30),
    Sale_Price float,
    Date_Sold date,
    Days_On_Market float
  )
"""

try:
  cur.execute(create_table_query)
  conn.commit()
  print("Sales Table Created Successfully.")

except mysql.connector.Error as e:
  print("Error: ", e)

Sales Table Created Successfully.

## Inserting Values into Tables

In [2928]:
# Inserting data into agents table
data_list = agents_df.values.tolist()
insert_query = """
  insert into agents (Agent_ID, Email, Phone, Commission_Rate, Deals_Closed, Rating, Years_Of_Experience, Avg_Closing_Days)
  values (%s, %s, %s, %s, %s, %s, %s, %s)
"""
try:
  cur.executemany(insert_query, data_list)
  conn.commit()
  print("Data inserted into agents table successfully. ")

except mysql.connector.Error as e:
  print('Error: ',e)

Data inserted into agents table successfully.

In [2929]:
#  Inserting data into buyers table
data_list = buyers_df.values.tolist()
insert_query = """
  insert into buyers (Buyer_ID, Listing_ID, Buyer_Type, Payment_Method, Loan_Taken, Loan_Provider, Loan_Amount)
  values (%s, %s, %s, %s, %s, %s,%s)
"""
try:
  cur.executemany(insert_query, data_list)
  conn.commit()
  print("Data inserted into buyers table successfully. ")

except mysql.connector.Error as e:
  print('Error: ',e)

Data inserted into buyers table successfully.

In [2930]:
# Inserting data into listings table
data_list = listings_df.values.tolist()
insert_query = """
  insert into listings (Listing_ID, City, Property_Type, Price, Sqft, Date_Listed, Agent_ID, Latitude, Longitude)
  values (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

try:
  cur.executemany(insert_query, data_list)
  conn.commit()
  print("Data inserted into listings table successfully. ")

except mysql.connector.Error as e:
  print('Error: ',e)

Data inserted into listings table successfully.

In [2931]:
# Inserting data into property_attributes table
data_list = prop_att_df.values.tolist()
insert_query = """
  insert into property_attributes (Attribute_ID, Listing_ID, Bedroom, Bathroom, Floor_Number, Total_Floor, Year_Built, Is_Rented, Tenant_Count, Furnishing_Status, Metro_Distance, Parking_Available, Power_Backup)
  values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

try:
  cur.executemany(insert_query, data_list)
  conn.commit()
  print("Data inserted into property_attributes table successfully. ")

except mysql.connector.Error as e:
  print('Error: ',e)

Data inserted into property_attributes table successfully.

In [2932]:
# Inserting data into sales table
data_list = sales_df.values.tolist()
insert_query = """
  insert into sales (Listing_ID, Sale_Price, Date_Sold, Days_On_Market)
  values (%s, %s, %s, %s)
"""

try:
  cur.executemany(insert_query, data_list)
  conn.commit()
  print("Data inserted into sales table successfully. ")

except mysql.connector.Error as e:
  print('Error: ',e)

Data inserted into sales table successfully.

## Property & Pricing Analysis

### Q1. What is the average listing price by city?

In [2933]:
query = """
  select
    City,
    round(avg(Price), 2) 
  from listings
  group by City;
"""
cur.execute(query)
result = cur.fetchall()

# Table Headers
headers = ['City', 'Avg_Price']
print(tabulate(result, headers=headers, tablefmt='grid'))

+-------------+-------------+
| City        |   Avg_Price |
+=============+=============+
| New York    | 2.49332e+06 |
+-------------+-------------+
| Los Angeles | 2.44242e+06 |
+-------------+-------------+
| Houston     | 2.43681e+06 |
+-------------+-------------+
| Phoenix     | 2.45996e+06 |
+-------------+-------------+
| Chicago     | 2.43068e+06 |
+-------------+-------------+

### Q2. What is the average price per square foot by property type?

In [2934]:
query = """
  with price_sqft as (
  select 
    property_type,
      round(sum(price), 2) as total_price,
      round(sum(sqft), 2) as total_sqft
  from listings
  group by property_type)
  select 
    property_type,
      round((total_price/total_sqft), 2) as price_per_sqft
  from price_sqft;
"""
cur.execute(query)
result = cur.fetchall()

# Define Headers
headers = ['Property_type', 'Price_Per_Sqft']
print(tabulate(result, headers=headers, tablefmt='grid'))

+-----------------+------------------+
| Property_type   |   Price_Per_Sqft |
+=================+==================+
| Apartment       |           479.84 |
+-----------------+------------------+
| Townhouse       |           484.1  |
+-----------------+------------------+
| House           |           484.31 |
+-----------------+------------------+
| Condo           |           470.73 |
+-----------------+------------------+

### Q3. How does furnishing status impact property prices

### Q4. Do properties closer to metro stations command higher prices?

In [2943]:
# Sample Query
query = "select * from agents"
cur.execute(query)
result = cur.fetchall()

# Define Headers
headers = ['Agent_ID', "Email", "Phone", "Commission_Rate", "Deals_Closed", "Rating", 'Years_Of_Experience', 'Avg_Closing_Days']
print(tabulate(result, headers=headers, tablefmt="grid"))

+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| Agent_ID   | Email                |        Phone |   Commission_Rate |   Deals_Closed |   Rating |   Years_Of_Experience |   Avg_Closing_Days |
+============+======================+==============+===================+================+==========+=======================+====================+
| A0001      | a0001@realestate.com | +15346658373 |              2    |             52 |      4.3 |                    10 |                 64 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0002      | a0002@realestate.com | +14934634698 |              2.2  |             26 |      3.8 |                    20 |                 82 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0003      | a0003@realestate.com | +12905341121 |              2.85 |            297 |      3.6 |                    21 |                 83 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0004      | a0004@realestate.com | +16916104878 |              1.67 |             31 |      4.5 |                     5 |                 61 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0005      | a0005@realestate.com | +18296135411 |              1.11 |            198 |      4.3 |                    16 |                 67 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0006      | a0006@realestate.com | +15206597012 |              1.58 |             63 |      4.9 |                     7 |                 49 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0007      | a0007@realestate.com | +11341388917 |              1.78 |            127 |      3.8 |                     4 |                 68 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0008      | a0008@realestate.com | +18214772854 |              1.72 |             74 |      3.4 |                    18 |                 72 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0009      | a0009@realestate.com | +16945932311 |              2.85 |            218 |      4.4 |                    18 |                 38 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0010      | a0010@realestate.com | +12458479624 |              2.14 |            292 |      3.4 |                    17 |                 90 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0011      | a0011@realestate.com | +19798685578 |              2.01 |            270 |      4.9 |                    23 |                 60 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0012      | a0012@realestate.com | +15766292281 |              2.37 |             24 |      3.5 |                    16 |                 82 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0013      | a0013@realestate.com | +16357242449 |              1.78 |             11 |      4.8 |                    14 |                 65 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0014      | a0014@realestate.com | +13515832279 |              1.97 |             60 |      3.7 |                    23 |                 85 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0015      | a0015@realestate.com | +18007489834 |              1.49 |             50 |      4.1 |                     2 |                 84 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0016      | a0016@realestate.com | +19176936119 |              1.45 |            230 |      4.8 |                    15 |                 31 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0017      | a0017@realestate.com | +17271546628 |              2.14 |            156 |      4.3 |                    19 |                 58 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0018      | a0018@realestate.com | +16478971176 |              2.63 |             89 |      4.1 |                    20 |                 39 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0019      | a0019@realestate.com | +15805649399 |              2.8  |             48 |      3.1 |                    25 |                 62 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0020      | a0020@realestate.com | +15806876431 |              2.67 |            166 |      5   |                    20 |                 65 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0021      | a0021@realestate.com | +15314615827 |              2.73 |            233 |      3.6 |                    21 |                 77 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0022      | a0022@realestate.com | +13962711578 |              1.94 |             56 |      3.2 |                    13 |                 44 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0023      | a0023@realestate.com | +18117115981 |              1.89 |             30 |      4.1 |                    18 |                 23 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0024      | a0024@realestate.com | +18449035267 |              2.95 |            283 |      4.1 |                     9 |                 79 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0025      | a0025@realestate.com | +11627448752 |              2.01 |            188 |      3.2 |                    14 |                 48 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0026      | a0026@realestate.com | +16922731845 |              1.63 |            225 |      5   |                    17 |                 42 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0027      | a0027@realestate.com | +17723981447 |              1.92 |            157 |      4.6 |                     5 |                 36 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0028      | a0028@realestate.com | +13935962351 |              2.25 |             69 |      4   |                    19 |                 33 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0029      | a0029@realestate.com | +12296172259 |              2.45 |             65 |      4.8 |                    16 |                 56 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0030      | a0030@realestate.com | +19719025552 |              2.79 |            296 |      3.3 |                    13 |                 77 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0031      | a0031@realestate.com | +13582355603 |              2.51 |            226 |      3.6 |                    20 |                 60 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0032      | a0032@realestate.com | +13819785209 |              2.57 |            151 |      3.3 |                    21 |                 33 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0033      | a0033@realestate.com | +11148592827 |              2.56 |             14 |      3.1 |                     3 |                 57 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0034      | a0034@realestate.com | +17182783476 |              2.46 |             83 |      3.1 |                     7 |                 31 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0035      | a0035@realestate.com | +17745577058 |              2.96 |            262 |      3.4 |                     1 |                 20 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0036      | a0036@realestate.com | +19272795280 |              1.73 |             98 |      3.7 |                    22 |                 69 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0037      | a0037@realestate.com | +19018174869 |              1.78 |             16 |      4.1 |                    15 |                 77 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0038      | a0038@realestate.com | +15962859640 |              1.22 |            257 |      4.3 |                    12 |                 84 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0039      | a0039@realestate.com | +19821336617 |              1.37 |            142 |      3.5 |                    21 |                 76 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0040      | a0040@realestate.com | +11862483525 |              1.58 |            153 |      4.8 |                     4 |                 52 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0041      | a0041@realestate.com | +19576077765 |              1.32 |             77 |      3.6 |                     5 |                 27 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0042      | a0042@realestate.com | +18884924898 |              2.24 |            231 |      4.3 |                    13 |                 21 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0043      | a0043@realestate.com | +17765503740 |              1.75 |             85 |      3.2 |                    20 |                 89 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0044      | a0044@realestate.com | +13156916653 |              1.45 |            236 |      3.6 |                    20 |                 35 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0045      | a0045@realestate.com | +11557575331 |              2.5  |             99 |      4.2 |                    25 |                 26 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0046      | a0046@realestate.com | +18739392900 |              1.57 |            135 |      3.2 |                    10 |                 58 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0047      | a0047@realestate.com | +11532718602 |              1.63 |             91 |      4   |                    16 |                 33 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0048      | a0048@realestate.com | +15085875937 |              1.34 |            266 |      4   |                    21 |                 15 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0049      | a0049@realestate.com | +15878649724 |              1.7  |             17 |      4.1 |                    14 |                 33 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+
| A0050      | a0050@realestate.com | +13394887390 |              2.56 |            109 |      3.5 |                    11 |                 68 |
+------------+----------------------+--------------+-------------------+----------------+----------+-----------------------+--------------------+